#!/usr/bin/festival

(define  (sleep t0 seconds)
    (if (< (- (time) t0) seconds)
        (sleep t0 seconds)
	0))

(define (loop times code)
    (if (eq? times  1)
	(eval code)
	(begin
	    (eval code)
	    (loop (- times 1) code))))

(SayText "Athletes to the line")
(sleep (time) 120)
(SayText "Five minutes preparation and sighting time... ")
(SayText "Start")
(define startTime (time))
(sleep startTime (+ (* 4 60) 30)) 
(SayText "30 seconds")
(sleep startTime (* 5 60))
(SayText "Stop, Unload")
(sleep (time) 30)
(SayText "Take your positions")
(sleep (time) 60)

(SayText "For the first competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 200)
(SayText "Stop")
(sleep (time) 15)

(SayText "For the next competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 200)
(SayText "Stop")
(sleep (time) 15)

(SayText "For the next competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 200)
(SayText "Stop. Unload.")
(sleep (time) 5)

(SayText "Seven minutes changeover and sighting time... start")
(define startTime (time))
(sleep startTime (- (* 7 60) 30)) 
(SayText "30 seconds")
(sleep startTime (* 7 60))
(SayText "Stop")

(loop 2 '(begin
    (SayText "For the next competition series, load")
    (sleep (time) 5)
    (SayText "Start")
    (sleep (time) 150)
    (SayText "Stop")
    (sleep (time) 15))

(SayText "For the next competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 150)
(SayText "Stop... Unload")
(sleep (time) 5)

(SayText "Nine minutes changeover and sighting time... start")
(define startTime (time))
(sleep startTime (- (* 9 60) 30)) 
(SayText "30 seconds")
(sleep startTime (* 9 60))
(SayText "Stop")

(loop 2 '(begin
    (SayText "For the next competition series, load")
    (sleep (time) 5)
    (SayText "Start")
    (sleep (time) 250)
    (SayText "Stop")
    (sleep (time) 15))

(loop 4 '(begin
    (SayText "For the next competition shot, load")
    (sleep (time) 5)
    (SayText "Start")
    (sleep (time) 50)
    (SayText "Stop")
    (sleep (time) 20)))
(SayText "For the next competition shot, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 50)
(SayText "Stop. Unload.")
(SayText "Results are final")

(quit)
