#!/usr/bin/festival

(define  (sleep t0 seconds)
    (if (< (- (time) t0) seconds)
        (sleep t0 seconds)
	0))

(define (loop times code)
    (if (eq? times  1)
	(eval code)
	(begin
	    (eval code)
	    (loop (- times 1) code))))

(SayText "Athletes to the line")
(sleep (time) 120)
(SayText "Five minutes preparation and sighting time, ")
(SayText "Start")
(define startTime (time))
(sleep startTime (+ (* 4 60) 30)) 
(SayText "30 seconds")
(sleep startTime (* 5 60))
(SayText "Stop, Unload")
(sleep (time) 60)
(SayText "For the first competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 250)
(SayText "Stop")
(sleep (time) 20)
(SayText "For the next competition series, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 250)
(SayText "Stop")
(sleep (time) 20)
(loop 20 '(begin
    (SayText "For the next competition shot, load")
    (sleep (time) 5)
    (SayText "Start")
    (sleep (time) 50)
    (SayText "Stop")
    (sleep (time) 20)))
(SayText "For the next competition shot, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 50)
(SayText "Stop. Unload.")
(SayText "Results are final")

(quit)
