#!/usr/bin/festival

(define  (sleep t0 seconds)
    (if (< (- (time) t0) seconds)
        (sleep t0 seconds)
	0))

(define (loop times code)
    (if (eq? times  1)
	(eval code)
	(begin
	    (eval code)
	    (loop (- times 1) code))))

(SayText "Athletes to the line")
(sleep (time) 10)
(SayText "Take your positions")
(SayText "Three minutes preparation and sighting time. ")
(SayText "Start")
(define startTime (time))
(sleep startTime (+ (* 2 60) 30)) 
(SayText "30 seconds")
(sleep startTime (* 3 60))
(SayText "Stop, Unload")
(sleep (time) 50)
(SayText "Take your positions")
(sleep (time) 10)
(SayText "For the first competition shot. Load")
(sleep (time) 5)
(sleep (time) 50)
(SayText "Stop")
(sleep (time) 15)))
(loop 29 '(begin
    (SayText "For the next competition shot, load")
    (sleep (time) 5)
    (SayText "Start")
    (sleep (time) 50)
    (SayText "Stop")
    (sleep (time) 15)))
(SayText "For the next competition shot, load")
(sleep (time) 5)
(SayText "Start")
(sleep (time) 50)
(SayText "Stop. Unload.")
(SayText "Results are final")

(quit)
